name: Hygiene

on:
  - pull_request

jobs:
  hygiene:
    name: Hygiene

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set-up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      # Dependencies
      - run: brew install shellcheck shfmt

      # Enable only if Makefile exists
      - id: makefile
        run: |
          if [ -f Makefile ]; then
            echo "exists=true" >>"$GITHUB_OUTPUT"
          else
            echo "exists=false" >>"$GITHUB_OUTPUT"
          fi

      # Check formatting with shfmt
      - run: make format-check
        if: ${{ steps.makefile.outputs.exists == 'true' }}

      # Check linting with shellcheck
      - run: make lint
        if: ${{ steps.makefile.outputs.exists == 'true' }}
